### ISSUE TITLE
Running script on hass.os

### ISSUE THREAD

**Issue by artspe** [dm82m/homeassistant-resol-km2#1]
Using latest hass.os you need to modify the path to 'python3 /config/scripts/deltasol_status.py'. Overall the script works fine.

**Comment by supermarcie** [comment]
I created a folder script below sconfig and added the deltasol_status.py script
but when I add the configuration in configuration.yaml 
Added this (added Resol: on top of the config)

Resol:
  - platform: command_line
    name: deltasol
    json_attributes:
      - "temperature_sensor_1"
      - "temperature_sensor_2"
      - "pump_speed_relay"
      - "operating_hours_relay"
    value_template: '{{ value_json.timestamp }}'
    command: 'python3 /config/scripts/deltasol_status.py'
    scan_interval: 300
  - platform: template
    sensors:
      deltasol_collector_temperature:
        friendly_name: "Kollektortemperatur"
        value_template: "{{ states.sensor.deltasol.attributes.temperature_sensor_1 }}"
        unit_of_measurement: '°C'
        device_class: 'temperature'  


then i get following error whith checking the config 
Component error: Resol - Integration 'Resol' not found.

any idea what is wrong?
it is also not possible to leave out the Resol: on top of the config

**Comment by dm82m** [comment]
You need to remove "Resol:", don't know why you put that, its not in my example config.

**Comment by supermarcie** [comment]
hi,
now the sensors are working but I don't retrieve any values.
How can I test that the python script is working?

**Comment by dm82m** [comment]
use a shell and execute it manually on your system: "python3 /path/to/your/file/deltasol_status.py". you could also try to directly access the url that you changed in the deltasol_status.py script with your browser and see what it gives you back.

**Comment by supermarcie** [comment]
when i execute python3 /path/to/your/file/deltasol_status.py with correct parameters then I get message that python3 command does not exist.
Running this in the terminal window of my home assistant

**Comment by dm82m** [comment]
try with python instead of python3

**Comment by supermarcie** [comment]
tried with python, but also not working.
I have a resol DL2 probably that is the reason that the script does not work

**Comment by dm82m** [comment]
if "python" is not found and if you get a message like "command does not exist" then it has nothing to do with KM2/DL2. Its based on your environment. But yes sure, with the DL2 you can stop testing, cause even if you would be able to execute the script it wont get any data then.
