### ISSUE TITLE
how to install this

### ISSUE THREAD

**Issue by xally-pt** [dm82m/homeassistant-resol-km2#2]
Hello, 
I've a Resol KM-2 module connected to my lan and I'm trying to get the sensors data in my Home Assistant.
I'm glad I found you code, but i'm a rookie in these things, so I can't get it to work.

I've edit the resol-km2.py file with the ip of the KM-2 and password.
But after that I'm lost.

I should place this file in a directory named "scripts" on the base of the system? (I created that directory) /scripts/resol-
km2.py

In the configuration.yaml file am I supposed to copy the rest of the instructions? Because every time I do that it reports an error abou the name. 
"
bad indentation of a mapping entry at line 3, column 9:
        name: deltasol
            ^
"

How do i know the script is running do i have do run it manually?

Your help would be very appreciated.

**Comment by dm82m** [comment]
Hey @xally-pt,

at first: please try to execute the script on your system. ```
python3 /scripts/resol-
km2.py
``` and tell me what output it will give you. If it is command not found, try with ```
python /scripts/resol-
km2.py
```

Best,
Dirk

**Comment by xally-pt** [comment]
Hello,
Sorry but no luck running the terminal.
Do I have to install python?


"
~ $ python3 /scripts/resol-km2.py
-bash: python3: command not found
~ $ python /scripts/resol-km2.py
-bash: python: command not found
~ $ 
"

**Comment by xally-pt** [comment]
Maybe i'm just doing it wrong.
I have home assistant installed in a Raspberry Pi 4, I run the command in the home assistant terminal. 
I also run it remotely using ssh from my mac terminal, but the result is the same.
I don't know much about home assistant or programming, I notice I don't have access to the root directory in HA terminal to all folders, when a do a ls comand I only see: addons; backup; config; share; and ssl.
I read in other place that python scripts should be in a directory called "python_scripts" inside the config directory.
I've tried that as well but again no success.
I'll see what i can learn about this. and I let you know when I can launch the script successfully.

**Comment by dm82m** [comment]
And how are you running Home Assistant on the Raspberry? What installation method have you used?

**Comment by xally-pt** [comment]
I’ve downloaded the image file of home assistant directly to sd card.

**Comment by xally-pt** [comment]
Instead of running trough terminal I ran the command in a place called "execute shell command" I used "python3 /config/python_scripts/resol-km2.py" and it return this:

Command executed: python3 /config/python_scripts/resol-km2.py: 1
Traceback (most recent call last):
  File "/config/python_scripts/resol-km2.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I used the comand shell to instal requests using "pip3 install requests" 
Ran the comand again and VOlLÁ!!! 

Command executed: python3 /config/python_scripts/resol-km2.py: 0
{"timestamp": "11.12.2020 23:18:09", "temperature_sensor_1": 629421608, "temperature_sensor_2": 16.3, "pump_speed_relay": 21.700000000000003, "operating_hours_relay": 0}

So what's the next move?

**Comment by dm82m** [comment]
Perfect, the script is working successfully! Now add the Sensor stuff to your configuration.yaml as described in my overview page

**Comment by xally-pt** [comment]
Hello,

So I  Copy paste the code in your overview page but i get a lot of erros in the editor.
  bad indentation of a mapping entry at line 3, column 9:
        name: "deltasol" 

Also I think your code is called resol-km2.py and not deltasol_status.py like your instructions .

I've changed the command to the one working for me:      `command: "python3 /config/python_scripts/resol-km2.py"` 
But I don't see anything happens.

Is this script continuously running just because he is in a python_scripts folder?
Isn't necessary to add something in configuration.yaml to run the script?
Sorry if these are strange questions, but for me this is a puzzle.

About the debug, temperature_sensor_1  is reading something else because temperature_sensor_2 is reading my actual sensor 1. The Pump_speed_relay it's showing 22 but it's actually is my 6th temperature sensor value. I thing maybe this is something about the address is not right.

My central has 6 temperature sensors and one pressure sensor connected to it.
you can see a live diagram of my system here:   [](https://www.vbus.net/L3Ma-3UD)

I'm Portuguese, and I live in an Island called Madeira, and you, where are you from?

**Comment by xally-pt** [comment]
Hello, I've managed to get this running 👍 
But like you said, it needs debbuging.
Where's a screenshot of my actual readings vs actual values in my deltasol.

![Captura de ecrã 2021-01-09, às 19 02 41 2](https://user-images.githubusercontent.com/70353913/104106609-14ffe080-52af-11eb-99e7-50ccaeb1932e.png)

At least 3 values are raid correct.
Can you help me with this?

**Comment by dm82m** [comment]
Please install the app [Postman](https://www.postman.com/downloads/) and import [this](https://www.dropbox.com/s/6enev63l55vw8y8/resol.postman_collection.json?dl=0) collection.

You need to execute the **login** first and modify the IP to your IP and within body you need to modify your password. As result you get the authId. That is what you will need next.

Second you need to execute the **dataGetCurrentData** and modify the IP to your IP and within body you need to insert the authId from the previous step. The response is what we need to modify my script to read the data you want to extract. Would be best if you send me the response.json and a screenshot as in your last post + the information what data you exactly want to extract.

**Comment by xally-pt** [comment]
Hello.
So, here's what you've asked.
If I'm not mistaken it should be it.

![selected info](https://user-images.githubusercontent.com/70353913/104967480-5e50de00-59db-11eb-8b57-b44aa9498ce4.jpeg)

[response.json.zip](https://github.com/dm82m/homeassistant-resol-km2/files/5832612/response.json.zip)

**Comment by dm82m** [comment]
try to replace these lines in my script. it should give you all the red marked data back. if you need to modify it, just upload your response.json [here](https://jsoneditoronline.org/) and navigate through the json and adapt it in the script.

```
data["timestamp"] = datetime.datetime.fromtimestamp(int(response[0]["result"]["headersets"][0]["packets"][0]["timestamp"])).strftime('%d.%m.%Y %H:%M:%S')
data["temperature_sensor_1"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][1]["raw_value"], 2)
data["temperature_sensor_2"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][2]["raw_value"], 2)
data["temperature_sensor_3"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][3]["raw_value"], 2)
data["temperature_sensor_4"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][4]["raw_value"], 2)
data["temperature_sensor_5"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][5]["raw_value"], 2)
data["temperature_vfs_rps"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][6]["raw_value"], 2)
data["pressure_aps"] = round(response[0]["result"]["headersets"][0]["packets"][0]["field_values"][10]["raw_value"], 2)
data["pump_speed_relay"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][11]["raw_value"]
data["pwm_a"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][15]["raw_value"]
data["error_overpressure"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][21]["raw_value"]
data["error_lowpressure"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][22]["raw_value"]
data["warning_too_high"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][27]["raw_value"]
data["warning_maximum_store_temperature"] = response[0]["result"]["headersets"][0]["packets"][0]["field_values"][30]["raw_value"]

```

**Comment by dm82m** [comment]
Found a way better solution for everything, just follow here: https://github.com/dm82m/hass-Deltasol-KM2
